app/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<uuid:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<uuid:product_id>/", views.cart_remove, name="cart_remove"),
]

app/config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("captcha/", include("captcha.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("catalog.api.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("account/", include("account.urls", namespace="account")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("order.urls", namespace="order")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("store.urls", namespace="store")),
]

if "debug_toolbar" in settings.INSTALLED_APPS and settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    )

handler404 = "store.views.page_not_found"
handler500 = "store.views.server_error"
handler403 = "store.views.permission_denied"

app/store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="home"),
    path("contact/", views.FeedbackFormView.as_view(), name="feedback"),
    path("<slug:slug>/", views.PageInfoDetailView.as_view(), name="page_info"),
]

app/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

app/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_POST

from catalog.models import Product
from order.forms import OrderCreateForm
from order.models import OrderItem
from order.tasks import order_created
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )
            # clear the cart
            cart.clear()
            # launch asynchronous task
            order_created.delay(order.id)
            # set the order in the session
            request.session["order_id"] = str(order.id)
            return render(request, "order/create.html", {"order": order})

    else:
        form = OrderCreateForm()
    return render(
        request,
        "cart/cart_detail.html",
        {
            "cart": cart,
            "form": form,
            "button_text": _("Checkout"),
        },
    )

app/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    {% translate "Shopping cart" %}
{% endblock title %}
{% block content %}
    {% if not cart %}
        <h1>{% translate "Your shopping cart is empty" %}</h1>
    {% else %}
        <h1>{% translate "Your shopping cart" %}</h1>
        <section class="cart">
            {% for item in cart %}
                {% with product=item.product %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col image">
                                    <a href="{{ product.get_absolute_url }}">
                                        {% if product.get_image %}
                                            <img width="60" src="{{ product.get_image }}" alt="{{ product.name }}">
                                        {% else %}
                                            <i class="fa fa-image"></i>
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="col name">
                                    <a href="{{ product.get_absolute_url }}" class="blue-link d-block mb-2">{{ product.name }}</a>
                                </div>
                                <div class="col ">
                                    <form action="{% url "cart:cart_add" product.id %}"
                                          method="post"
                                          class="cart-quantity d-flex align-items-center justify-content-center">
                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.override }}
                                        {% csrf_token %}
                                        <button type="submit"
                                                aria-label="Update"
                                                class="update-btn d-flex align-items-center justify-content-center">
                                            <i class="fa fa-check"></i>
                                        </button>
                                    </form>
                                </div>
                                <div class="col checkout-cart-price">
                                    *
                                    {{ item.price }}{{ currency }}
                                </div>
                                <div class="col checkout-cart-total">
                                    =
                                    {{ item.total_price }}{{ currency }}
                                </div>
                                <div class="col cart_remove">
                                    <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit"
                                                aria-label="Remove"
                                                class="delete-btn d-flex align-items-center justify-content-center">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
            <div class="card-body cart-total">
                <b>Total</b>: {{ cart.get_total_price }}{{ currency }}
            </div>
            {% include "store/components/form.html" with button=button_text %}
        </section>
    {% endif %}
    <hr>
    <div class="row">
        <div class="col">
            <i class="fa fa-long-arrow-alt-left me-2"></i>
            <a href="{% url "store:home" %}" class="button light">{% translate "Continue shopping" %}</a>
        </div>
    </div>
{% endblock content %}