app/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<uuid:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<uuid:product_id>/", views.cart_remove, name="cart_remove"),
]

app/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index_view, name="rooms"),
    path("<str:room_name>/", views.room_view, name="room"),
]

app/config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("captcha/", include("captcha.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("catalog.api.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("account/", include("account.urls", namespace="account")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("order.urls", namespace="order")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("store.urls", namespace="store")),
]

if "debug_toolbar" in settings.INSTALLED_APPS and settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    )

handler404 = "store.views.page_not_found"
handler500 = "store.views.server_error"
handler403 = "store.views.permission_denied"

app/store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="home"),
    path("contact/", views.FeedbackFormView.as_view(), name="feedback"),
    path("<slug:slug>/", views.PageInfoDetailView.as_view(), name="page_info"),
]

app/templates/base.html
{% spaceless %}
    {% load static %}
    {% load i18n %}
    <!DOCTYPE html>
    <html lang="{{ lang }}">
        <head>
            <title>
                {% block title %}
                    {{ title }} | {{ store_name }}
                {% endblock title %}
            </title>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <meta name="keywords" content="{{ meta_keywords }}">
            <meta name="description" content="{{ meta_description }}">
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="{% static 'store/img/favicon.png' %}"
                  rel="icon"
                  type="image/png" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
                  rel="stylesheet"
                  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
                  crossorigin="anonymous">
            <link type="text/css"
                  href="{% static 'store/css/style.css' %}"
                  rel="stylesheet" />
            <link type="text/css"
                  href="{% static 'store/css/icon.css' %}"
                  rel="stylesheet" />
            <link type="text/css"
                  href="{% static 'store/css/adaptive.css' %}"
                  rel="stylesheet" />
        </head>
        <body>
            <header>
                <div class="container">
                    <div class="flex">
                        <div class="logo">
                            <a class="logo-link" href="{% url "store:home" %}"><i class="fa fa-store"></i><span class="store_name">{{ store_name }}</span></a>
                        </div>
                        {% include "store/components/store_contacts.html" %}
                        {% block header_menu %}
                            <nav id="top_menu">
                                <ul>
                                    {% for tm in top_menu %}
                                        <li>
                                            <a href="{{ tm.get_absolute_url }}">{{ tm.name }}</a>
                                        </li>
                                    {% endfor %}
                                    <li>
                                        <a href="{% url "store:feedback" %}">{% translate "Contact us" %}</a>
                                    </li>
                                    <li>
                                        <a href="{% url "chat:rooms" %}">{% translate "Chat" %}</a>
                                    </li>
                                    {% include "account/components/header_login.html" %}
                                </ul>
                            </nav>
                        {% endblock header_menu %}
                        {% include "cart/components/header_cart.html" %}
                    </div>
                </div>
            </header>
            {% if breadcrumbs %}
                <div class="container">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a class="breadcrumb-item-link" href="{% url "store:home" %}"><i class="fa fa-home"></i><span class="visually-hidden">{% translate "Home" %}</span></a>
                            </li>
                            {% block breadcrumbs %}
                                {{ breadcrumbs }}
                            {% endblock breadcrumbs %}
                        </ol>
                    </nav>
                </div>
            {% endif %}
            {% if title_section %}
                {% block title_section %}
                    {% if title_page %}
                        <style>
                    #title_section {
                        background:
                        {% if title_image_url %}
                            url('{{ title_image_url }}') 50% 0 no-repeat;
                        {% else %}
                            rgb(252 175 42 / 40%);
                        {% endif %}
                        background-size: cover;
                    }
                        </style>
                        <section id="title_section" class="pm-30">
                            <div class="container">
                                <h1>{{ title_page }}</h1>
                            </div>
                            {% if title_page %}<div class="container pt-20">{{ title_description|safe }}</div>{% endif %}
                        </section>
                    {% endif %}
                {% endblock title_section %}
            {% endif %}
            <main class="pb-20">
                <div class="container">
                    {% block content %}
                    {% endblock content %}
                </div>
            </main>
            <footer>
                <div class="container">
                    <div class="flex">
                        <div class="col footer__logo">
                            <div class="logo">
                                <a class="logo-link" href="{% url "store:home" %}"><i class="fa fa-store"></i><span class="store_name">{{ store_name }}</span></a>
                            </div>
                            {% if store_description %}{{ store_description|safe }}{% endif %}
                        </div>
                        {% block footer_menu %}
                            {% if bottom_menu %}
                                <div class="col col__nav">
                                    <div class="title">{% translate "Useful information" %}</div>
                                    <ul>
                                        {% for bm in bottom_menu %}
                                            <li>
                                                <a href="{{ bm.get_absolute_url }}">{{ bm.name }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                        {% endblock footer_menu %}
                        <div class="col col__nav">
                            <div class="title">{% translate "Product Categories" %}</div>
                            {% include "store/components/footer_categories.html" %}
                        </div>
                        <div class="col col__nav">
                            <div class="title">{% translate "Contacts" %}</div>
                            {% include "store/components/store_contacts.html" %}
                            <ul>
                                <li>
                                    <a href="{% url "store:feedback" %}">{% translate "Contact us" %}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="copyright flex">
                        {% now "Y" as current_year %}
                        <p>
                            <a href="{% url "store:home" %}">{{ store_name }}</a> © {{ current_year }}
                        </p>
                    </div>
                </div>
            </footer>
        </body>
    </html>
{% endspaceless %}